<a href="https://colab.research.google.com/github/DenShum/NumPy-pandas-MPL/blob/main/pal_8_Denis_Shum_dz_nampy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [ ]:
import numpy as np

a = np.arange(0,10)
x = a[::-1]
x


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
b = np.array([9,8,7,6,5,4,3,2,1,0])
b

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [ ]:
data = np.diag(x, k=0)
data


array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
data = np.diag(x, k=0) # сумма элементов диагонали 1 вариант
res = 0
index = 0
for row in data:
  res += row[index]
  index += 1
  print(res)

9
17
24
30
35
39
42
44
45
45


In [ ]:
diag_ = np.diagonal(data) #сумма элементов диагонали 2 вариант
diag_sum = sum(diag_)
diag_sum

45

Задание 3
Решите систему уравнений:
4x + 2y + z = 4;
x + 3y = 12;
5y + 4z = -3

In [ ]:
c = np.array([[4,2,1],[1,3,0],[5,4,0]])
d = np.array([4,12,-3])
from numpy import linalg
linalg.solve(c,d)

array([-5.18181818,  5.72727273, 13.27272727])

Задание 4
В материалах занятия раздел “Задача 4 домашнего задания”


In [ ]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ]
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])
next_user_statsLength = np.linalg.norm(next_user_stats)

def cosine():
  index = 0
  for i,user in enumerate(users_stats):
    user_Length = np.linalg.norm(users_stats[index])
    x = np.dot(next_user_stats,users_stats[index])/(next_user_statsLength*user_Length)
    index += 1
    print(i+1,x) ##Пользователь с ID 8 наиболее похож на нового пользователя

cosine()


1 0.19999999999999996
2 0.8451542547285165
3 0.3999999999999999
4 0.7905694150420948
5 0.3999999999999999
6 0.0
7 0.0
8 0.9486832980505138
9 0.0
10 0.0


In [ ]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ]
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])
next_user_statsLength = np.linalg.norm(next_user_stats)
def cosine():
    user0_Length = np.linalg.norm(users_stats[0])
    user0 = np.dot(next_user_stats,users_stats[0])/(next_user_statsLength*user0_Length)
    user1_Length = np.linalg.norm(users_stats[1])
    user1 = np.dot(next_user_stats,users_stats[1])/(next_user_statsLength*user1_Length)
    user2_Length = np.linalg.norm(users_stats[2])
    user2 = np.dot(next_user_stats,users_stats[2])/(next_user_statsLength*user2_Length)
    user3_Length = np.linalg.norm(users_stats[3])
    user3 = np.dot(next_user_stats,users_stats[3])/(next_user_statsLength*user3_Length)
    user4_Length = np.linalg.norm(users_stats[4])
    user4 = np.dot(next_user_stats,users_stats[4])/(next_user_statsLength*user4_Length)
    user5_Length = np.linalg.norm(users_stats[5])
    user5 = np.dot(next_user_stats,users_stats[5])/(next_user_statsLength*user5_Length)
    user6_Length = np.linalg.norm(users_stats[6])
    user6 = np.dot(next_user_stats,users_stats[6])/(next_user_statsLength*user6_Length) 
    user7_Length = np.linalg.norm(users_stats[7])
    user7 = np.dot(next_user_stats,users_stats[7])/(next_user_statsLength*user7_Length)
    user8_Length = np.linalg.norm(users_stats[8])
    user8 = np.dot(next_user_stats,users_stats[8])/(next_user_statsLength*user8_Length)
    user9_Length = np.linalg.norm(users_stats[9])
    user9 = np.dot(next_user_stats,users_stats[9])/(next_user_statsLength*user9_Length)
    print(user0)
    print(user1)
    print(user2)
    print(user3)
    print(user4)
    print(user5)
    print(user6)
    print(user7)#Пользователь с ID 8 наиболее похож на нового пользователя
    print(user8)
    print(user9)

cosine()

0.19999999999999996
0.8451542547285165
0.3999999999999999
0.7905694150420948
0.3999999999999999
0.0
0.0
0.9486832980505138
0.0
0.0
